filter:
    paths:
        - 'app/*'
    excluded_paths:
        - 'app/views/*'
        - 'app/config/*'
        - 'app/database/*'
checks:
    php:
      code_rating: true
      duplication: true
coding_style:
    php:
        spaces:
            within:
                brackets: true
build: true